language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "pypy"
install:
  - pip install -r requirements.txt
  - pip install .
before_script:
  - sleep 10
script:
  - coverage run --source pytsdb -m py.test
after_success:
  - coveralls
services:
  - redis-server
  - cassandra